import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-around h-28 items-center">
        <Image
          className="h-0.5"
          src="/assests/images/logo.svg"
          alt="website logo"
          width={100}
          height={100}
        ></Image>

        <ul className="nav-links lg:flex hidden lg:block">
          <li>Pricing</li>
          <li>Product</li>
          <li>About Us</li>
          <li>Careers</li>
          <li>Community</li>
        </ul>

        <button className="started lg:flex hidden lg:block">Get Started</button>

        <Image
          src="/assests/images/icon-hamburger.svg"
          alt="hamburger"
          width={50}
          height={50}
        ></Image>
      </nav>

      {/* <img src="/assests/images/icon-hamburger.svg" alt="" />
      <img src="/assests/images/logo.svg" alt="" /> */}
    </>
  );
}
