import Head from "next/head";
import { hamLogo, logoIcon } from "../data/icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex justify-around h-28 items-center">
        <div className="logo">{logoIcon()}</div>

        <ul className="nav-links lg:flex hidden lg:block lg:justify-around lg:w-2/4">
          <li>Pricing</li>
          <li>Product</li>
          <li>About Us</li>
          <li>Careers</li>
          <li>Community</li>
        </ul>

        <button className="started lg:flex hidden lg:block bg-otherOrange font-bold">
          Get Started
        </button>

        <div className="ham lg:hidden">{hamLogo()}</div>
      </nav>
    </>
  );
}
